# Generated by Django 6.0.5 on 2026-06-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sertifikasi', models.CharField(max_length=200)),
                ('deskripsi_singkat', models.TextField()),
                ('gambar_sertifikat', models.ImageField(upload_to='certs/')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_kegiatan', models.CharField(max_length=200)),
                ('penjelasan', models.TextField()),
                ('pelajaran_didapat', models.TextField()),
                ('gambar_kegiatan', models.ImageField(upload_to='experience/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('bio_singkat', models.TextField()),
                ('pendidikan_terakhir', models.CharField(default='S1 Informatika UPJ', max_length=255)),
                ('foto', models.ImageField(upload_to='profile/')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('kategori', models.CharField(choices=[('language', 'Language'), ('framework', 'Framework'), ('tool', 'Tool/Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('github_link', models.URLField(blank=True)),
                ('gambar', models.ImageField(upload_to='projects/')),
                ('skills_learned', models.ManyToManyField(to='api.skill')),
            ],
        ),
    ]
