# Generated by Django 6.0.5 on 2026-06-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills_raw',
            field=models.TextField(default=1, help_text='Pisahkan dengan koma, contoh: Python,Django,Next.js'),
            preserve_default=False,
        ),
    ]
