# Generated by Django 6.0.5 on 2026-06-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_skills_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills_raw',
            field=models.TextField(blank=True, help_text='Pisahkan dengan koma, contoh: Python,Django,Next.js', null=True),
        ),
    ]
