# Generated by Django 6.0.5 on 2026-06-24 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_skills_raw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='gambar_kegiatan',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='pelajaran_didapat',
        ),
    ]
